#!/bin/sh

echo "Running lint-staged checks..."
yarn lint-staged

# Only run tests on staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(ts|tsx)$' | grep -v "node_modules")

if [ -n "$STAGED_FILES" ]; then
  echo "Running tests on staged files..."
  yarn test --watchAll=false --findRelatedTests $STAGED_FILES
fi 